/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Prueba;

/**
 *
 * @author software_07
 */
public class AñadirRegistro extends javax.swing.JFrame {

    /**
     * Creates new form AñadirRegistro
     */
    public AñadirRegistro() {
        initComponents();
        lblCampo1.setVisible(false);
        lblCampo2.setVisible(false);
        lblCampo3.setVisible(false);
        lblCampo4.setVisible(false);
        lblCampo5.setVisible(false);
        lblCampo6.setVisible(false);
        
        cbCampo1.setVisible(false);
        cbCampo2.setVisible(false);
        cbCampo3.setVisible(false);
        cbCampo4.setVisible(false);
        cbCampo5.setVisible(false);
        cbCampo6.setVisible(false);
        
        txtCampo1.setVisible(false);
        txtCampo2.setVisible(false);
        txtCampo3.setVisible(false);
        txtCampo4.setVisible(false);
        txtCampo5.setVisible(false);
        txtCampo6.setVisible(false);
        
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblCampo1 = new javax.swing.JLabel();
        setVisible(false);
        lblCampo2 = new javax.swing.JLabel();
        setVisible(false);
        lblCampo3 = new javax.swing.JLabel();
        setVisible(false);
        lblCampo4 = new javax.swing.JLabel();
        setVisible(false);
        lblCampo5 = new javax.swing.JLabel();
        setVisible(false);
        lblCampo6 = new javax.swing.JLabel();
        setVisible(false);
        txtCampo1 = new javax.swing.JTextField();
        setVisible(false);
        txtCampo2 = new javax.swing.JTextField();
        setVisible(false);
        txtCampo3 = new javax.swing.JTextField();
        setVisible(false);
        txtCampo4 = new javax.swing.JTextField();
        setVisible(false);
        txtCampo5 = new javax.swing.JTextField();
        setVisible(false);
        txtCampo6 = new javax.swing.JTextField();
        setVisible(false);
        jScrollPane1 = new javax.swing.JScrollPane();
        tbInserts = new javax.swing.JTable();
        btnQuitar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        cbCampo1 = new javax.swing.JComboBox<>();
        setVisible(false);
        cbCampo2 = new javax.swing.JComboBox<>();
        setVisible(false);
        cbCampo3 = new javax.swing.JComboBox<>();
        setVisible(false);
        cbCampo4 = new javax.swing.JComboBox<>();
        setVisible(false);
        cbCampo5 = new javax.swing.JComboBox<>();
        setVisible(false);
        cbCampo6 = new javax.swing.JComboBox<>();
        setVisible(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 1000));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTitulo.setText("Titulo");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        lblCampo1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCampo1.setText("Campo1");
        getContentPane().add(lblCampo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        lblCampo1.getAccessibleContext().setAccessibleName("");

        lblCampo2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCampo2.setText("Campo2");
        getContentPane().add(lblCampo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        lblCampo2.getAccessibleContext().setAccessibleName("");

        lblCampo3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCampo3.setText("Campo3");
        getContentPane().add(lblCampo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));
        lblCampo3.getAccessibleContext().setAccessibleName("");

        lblCampo4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCampo4.setText("Campo4");
        lblCampo4.setOpaque(true);
        getContentPane().add(lblCampo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));
        lblCampo4.getAccessibleContext().setAccessibleName("");
        lblCampo4.getAccessibleContext().setAccessibleDescription("");

        lblCampo5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCampo5.setText("Campo5");
        lblCampo5.setOpaque(true);
        getContentPane().add(lblCampo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));
        lblCampo5.getAccessibleContext().setAccessibleName("");
        lblCampo5.getAccessibleContext().setAccessibleDescription("");

        lblCampo6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblCampo6.setText("Campo6");
        lblCampo6.setOpaque(true);
        getContentPane().add(lblCampo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));
        lblCampo6.getAccessibleContext().setAccessibleName("");
        lblCampo6.getAccessibleContext().setAccessibleDescription("");

        txtCampo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCampo1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtCampo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 740, 30));
        txtCampo1.getAccessibleContext().setAccessibleName("");

        txtCampo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCampo2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtCampo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 740, 30));
        txtCampo2.getAccessibleContext().setAccessibleName("");

        txtCampo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCampo3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtCampo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 740, 30));
        txtCampo3.getAccessibleContext().setAccessibleName("");

        txtCampo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCampo4ActionPerformed(evt);
            }
        });
        getContentPane().add(txtCampo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 740, 30));
        txtCampo4.getAccessibleContext().setAccessibleName("");
        txtCampo4.getAccessibleContext().setAccessibleDescription("");

        txtCampo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCampo5ActionPerformed(evt);
            }
        });
        getContentPane().add(txtCampo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 740, 30));
        txtCampo5.getAccessibleContext().setAccessibleName("");
        txtCampo5.getAccessibleContext().setAccessibleDescription("");

        txtCampo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCampo6ActionPerformed(evt);
            }
        });
        getContentPane().add(txtCampo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 740, 30));
        txtCampo6.getAccessibleContext().setAccessibleName("");
        txtCampo6.getAccessibleContext().setAccessibleDescription("");

        tbInserts.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tbInserts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbInserts.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbInserts);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 1090, 160));

        btnQuitar.setText("Quitar");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });
        getContentPane().add(btnQuitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 710, 80, 30));

        btnAgregar.setText("Agregar");
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 710, 80, 30));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 700, 130, 60));

        cbCampo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCampo1ActionPerformed(evt);
            }
        });
        getContentPane().add(cbCampo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 740, -1));
        cbCampo1.getAccessibleContext().setAccessibleName("");

        getContentPane().add(cbCampo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 740, -1));
        cbCampo2.getAccessibleContext().setAccessibleName("");

        getContentPane().add(cbCampo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 740, -1));
        cbCampo3.getAccessibleContext().setAccessibleName("");

        getContentPane().add(cbCampo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 740, -1));
        cbCampo4.getAccessibleContext().setAccessibleName("");
        cbCampo4.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(cbCampo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 740, -1));
        cbCampo5.getAccessibleContext().setAccessibleName("");
        cbCampo5.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(cbCampo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 740, -1));
        cbCampo6.getAccessibleContext().setAccessibleName("");
        cbCampo6.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCampo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCampo1ActionPerformed

    private void txtCampo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCampo2ActionPerformed

    private void txtCampo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCampo3ActionPerformed

    private void txtCampo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCampo4ActionPerformed

    private void txtCampo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampo5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCampo5ActionPerformed

    private void txtCampo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampo6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCampo6ActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void cbCampo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCampo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCampo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AñadirRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnQuitar;
    public javax.swing.JComboBox<String> cbCampo1;
    public javax.swing.JComboBox<String> cbCampo2;
    public javax.swing.JComboBox<String> cbCampo3;
    public javax.swing.JComboBox<String> cbCampo4;
    public javax.swing.JComboBox<String> cbCampo5;
    public javax.swing.JComboBox<String> cbCampo6;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblCampo1;
    public javax.swing.JLabel lblCampo2;
    public javax.swing.JLabel lblCampo3;
    public javax.swing.JLabel lblCampo4;
    public javax.swing.JLabel lblCampo5;
    public javax.swing.JLabel lblCampo6;
    public javax.swing.JLabel lblTitulo;
    public javax.swing.JTable tbInserts;
    public javax.swing.JTextField txtCampo1;
    public javax.swing.JTextField txtCampo2;
    public javax.swing.JTextField txtCampo3;
    public javax.swing.JTextField txtCampo4;
    public javax.swing.JTextField txtCampo5;
    public javax.swing.JTextField txtCampo6;
    // End of variables declaration//GEN-END:variables
}
