/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto.Vista;

import Proyecto.Controlador.Controlador;
import java.awt.BorderLayout;

/**
 * Fecha: 26/06/2022
 * @author Pedro Antonio Sanchez Salas, Ruy Jese Luna Sandoval, Juan Carlos Moreno Lopez, Jesus de Israel Jimenez Tostado, Erick Jeanick Lopez Gonzalez
 * Descripcion: Ventana principal del programa
 */
public class MenuPrincipal extends javax.swing.JFrame {

    
    public MenuPrincipal() {
        initComponents();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        content = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMenuPrincipal = new javax.swing.JMenu();
        menuItemPrincipal = new javax.swing.JMenuItem();
        menuTablas = new javax.swing.JMenu();
        menuTablasMuelle = new javax.swing.JMenuItem();
        menuTablasDique = new javax.swing.JMenuItem();
        menuTablaCasetas = new javax.swing.JMenuItem();
        menuTablasBarco = new javax.swing.JMenuItem();
        menuItemEmpleados = new javax.swing.JMenuItem();
        menuItemEntrada = new javax.swing.JMenuItem();
        menuItemSalidas = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenu();
        menuItemClientes = new javax.swing.JMenuItem();
        menuEstadoCuenta = new javax.swing.JMenu();
        menuItemEstadoCuenta = new javax.swing.JMenuItem();
        menuFolio = new javax.swing.JMenu();
        menuItemFolio = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal");

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1226, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
        );

        menuMenuPrincipal.setText("Menu Principal");

        menuItemPrincipal.setText("Menu Principal");
        menuItemPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPrincipalActionPerformed(evt);
            }
        });
        menuMenuPrincipal.add(menuItemPrincipal);

        jMenuBar1.add(menuMenuPrincipal);

        menuTablas.setText("Tablas");

        menuTablasMuelle.setText("Muelles");
        menuTablasMuelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTablasMuelleActionPerformed(evt);
            }
        });
        menuTablas.add(menuTablasMuelle);

        menuTablasDique.setText("Dique Seco");
        menuTablasDique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTablasDiqueActionPerformed(evt);
            }
        });
        menuTablas.add(menuTablasDique);

        menuTablaCasetas.setText("Casetas");
        menuTablaCasetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTablaCasetasActionPerformed(evt);
            }
        });
        menuTablas.add(menuTablaCasetas);

        menuTablasBarco.setText("Barcos");
        menuTablasBarco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTablasBarcoActionPerformed(evt);
            }
        });
        menuTablas.add(menuTablasBarco);

        menuItemEmpleados.setText("Empleados");
        menuTablas.add(menuItemEmpleados);

        menuItemEntrada.setText("Entradas");
        menuTablas.add(menuItemEntrada);

        menuItemSalidas.setText("Salidas");
        menuTablas.add(menuItemSalidas);

        jMenuBar1.add(menuTablas);

        menuClientes.setText("Clientes");

        menuItemClientes.setText("Clientes");
        menuItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemClientesActionPerformed(evt);
            }
        });
        menuClientes.add(menuItemClientes);

        jMenuBar1.add(menuClientes);

        menuEstadoCuenta.setText("Estados de Cuenta");

        menuItemEstadoCuenta.setText("Estado de Cuenta");
        menuItemEstadoCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEstadoCuentaActionPerformed(evt);
            }
        });
        menuEstadoCuenta.add(menuItemEstadoCuenta);

        jMenuBar1.add(menuEstadoCuenta);

        menuFolio.setText("Folio");

        menuItemFolio.setText("Folio");
        menuItemFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFolioActionPerformed(evt);
            }
        });
        menuFolio.add(menuItemFolio);

        jMenuBar1.add(menuFolio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuTablasMuelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTablasMuelleActionPerformed
        
    }//GEN-LAST:event_menuTablasMuelleActionPerformed

    private void menuTablasDiqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTablasDiqueActionPerformed
        
    }//GEN-LAST:event_menuTablasDiqueActionPerformed

    private void menuItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemClientesActionPerformed
        
    }//GEN-LAST:event_menuItemClientesActionPerformed

    private void menuTablaCasetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTablaCasetasActionPerformed
        
    }//GEN-LAST:event_menuTablaCasetasActionPerformed

    private void menuItemEstadoCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEstadoCuentaActionPerformed
        
    }//GEN-LAST:event_menuItemEstadoCuentaActionPerformed

    private void menuItemFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFolioActionPerformed
        
    }//GEN-LAST:event_menuItemFolioActionPerformed

    private void menuTablasBarcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTablasBarcoActionPerformed
        
    }//GEN-LAST:event_menuTablasBarcoActionPerformed

    private void menuItemPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPrincipalActionPerformed
        
    }//GEN-LAST:event_menuItemPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel content;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenu menuEstadoCuenta;
    public javax.swing.JMenu menuFolio;
    public javax.swing.JMenuItem menuItemClientes;
    public javax.swing.JMenuItem menuItemEmpleados;
    public javax.swing.JMenuItem menuItemEntrada;
    public javax.swing.JMenuItem menuItemEstadoCuenta;
    public javax.swing.JMenuItem menuItemFolio;
    public javax.swing.JMenuItem menuItemPrincipal;
    public javax.swing.JMenuItem menuItemSalidas;
    public javax.swing.JMenu menuMenuPrincipal;
    public javax.swing.JMenuItem menuTablaCasetas;
    public javax.swing.JMenu menuTablas;
    public javax.swing.JMenuItem menuTablasBarco;
    public javax.swing.JMenuItem menuTablasDique;
    public javax.swing.JMenuItem menuTablasMuelle;
    // End of variables declaration//GEN-END:variables
}
