/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto;

import java.awt.BorderLayout;

/**
 * Fecha: 26/06/2022
 * @author Pedro Antonio Sanchez Salas, Ruy Jese Luna Sandoval, Juan Carlos Moreno Lopez, Jesus de Israel Jimenez Tostado, Erick Jeanick Lopez Gonzalez
 * Descripcion: Ventana principal del programa
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        
        PanelPrincipal pp = new PanelPrincipal();
        pp.setSize(979, 473);
        pp.setLocation(0,0);
        
        content.removeAll();
        content.add(pp, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuTablas = new javax.swing.JMenu();
        menuTablasMuelle = new javax.swing.JMenuItem();
        menuTablasDique = new javax.swing.JMenuItem();
        menuTablaCasetas = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenu();
        menuItemClientes = new javax.swing.JMenuItem();
        menuEstadoCuenta = new javax.swing.JMenu();
        menuItemEstadoCuenta = new javax.swing.JMenuItem();
        menuFolio = new javax.swing.JMenu();
        menuItemFolio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal");

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 979, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        menuTablas.setText("Tablas");

        menuTablasMuelle.setText("Muelles");
        menuTablasMuelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTablasMuelleActionPerformed(evt);
            }
        });
        menuTablas.add(menuTablasMuelle);

        menuTablasDique.setText("Dique Seco");
        menuTablasDique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTablasDiqueActionPerformed(evt);
            }
        });
        menuTablas.add(menuTablasDique);

        menuTablaCasetas.setText("Casetas");
        menuTablaCasetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTablaCasetasActionPerformed(evt);
            }
        });
        menuTablas.add(menuTablaCasetas);

        jMenuBar1.add(menuTablas);

        menuClientes.setText("Clientes");

        menuItemClientes.setText("Clientes");
        menuItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemClientesActionPerformed(evt);
            }
        });
        menuClientes.add(menuItemClientes);

        jMenuBar1.add(menuClientes);

        menuEstadoCuenta.setText("Estados de Cuenta");

        menuItemEstadoCuenta.setText("Estado de Cuenta");
        menuItemEstadoCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEstadoCuentaActionPerformed(evt);
            }
        });
        menuEstadoCuenta.add(menuItemEstadoCuenta);

        jMenuBar1.add(menuEstadoCuenta);

        menuFolio.setText("Folio");

        menuItemFolio.setText("Folio");
        menuItemFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFolioActionPerformed(evt);
            }
        });
        menuFolio.add(menuItemFolio);

        jMenuBar1.add(menuFolio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuTablasMuelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTablasMuelleActionPerformed
        PanelTablaMuelles ptm = new PanelTablaMuelles();
        ptm.setSize(979, 473);
        ptm.setLocation(0,0);
        
        content.removeAll();
        content.add(ptm, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        
    }//GEN-LAST:event_menuTablasMuelleActionPerformed

    private void menuTablasDiqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTablasDiqueActionPerformed
        PanelTablaDiqueSeco ptd = new PanelTablaDiqueSeco();
        ptd.setSize(979, 473);
        ptd.setLocation(0,0);
        
        content.removeAll();
        content.add(ptd, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_menuTablasDiqueActionPerformed

    private void menuItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemClientesActionPerformed
        PanelClientes pc = new PanelClientes();
        pc.setSize(979, 473);
        pc.setLocation(0,0);
        
        content.removeAll();
        content.add(pc, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_menuItemClientesActionPerformed

    private void menuTablaCasetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTablaCasetasActionPerformed
        PanelTablaCaseta ptc = new PanelTablaCaseta();
        ptc.setSize(979, 473);
        ptc.setLocation(0,0);
        
        content.removeAll();
        content.add(ptc, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_menuTablaCasetasActionPerformed

    private void menuItemEstadoCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEstadoCuentaActionPerformed
        PanelEstadoCuenta pec = new PanelEstadoCuenta();
        pec.setSize(979, 473);
        pec.setLocation(0,0);
        
        content.removeAll();
        content.add(pec, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_menuItemEstadoCuentaActionPerformed

    private void menuItemFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFolioActionPerformed
        PanelFolio pf = new PanelFolio();
        pf.setSize(979, 473);
        pf.setLocation(0,0);
        
        content.removeAll();
        content.add(pf, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_menuItemFolioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenu menuEstadoCuenta;
    private javax.swing.JMenu menuFolio;
    private javax.swing.JMenuItem menuItemClientes;
    private javax.swing.JMenuItem menuItemEstadoCuenta;
    private javax.swing.JMenuItem menuItemFolio;
    private javax.swing.JMenuItem menuTablaCasetas;
    private javax.swing.JMenu menuTablas;
    private javax.swing.JMenuItem menuTablasDique;
    private javax.swing.JMenuItem menuTablasMuelle;
    // End of variables declaration//GEN-END:variables
}
